language: r
cache: packages

matrix:
  include:
    - os: linux
      env:
        - R_CODECOV=true
        - R_VERSION=stable
        - LINTR_COMMENT_BOT=false
    - os: linux
      env:
        - R_VERSION=devel
        - LINTR_COMMENT_BOT=false
    - os: linux
      env:
        - R_VERSION=oldrel
        - LINTR_COMMENT_BOT=false
    - os: osx
      osx_image: xcode8.3

r_github_packages:
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${{R_CODECOV}}" ]]; then R -e 'covr::codecov()'; fi
