language: r
sudo: false
cache: packages

r_github_packages:
  - hadley/testthat
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::coveralls()'
